services:
  - type: web
    name: mecanica-backend
    env: node
    region: ohio
    plan: free
    startCommand: cd backend && npm run build && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
